const Discord = require('discord.js');
const client = new Discord.Client();
console.log("Scrpit By Dream");


client.on("ready", () => {
let channel =     client.channels.get("508244132934844416")
setInterval(function() {
channel.send(`abcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyz`);
}, 25)
})
 
 
client.login('NDM2OTE4MTIwMTg0MDIxMDEy.DbugMg.DzE4jtPglXfN8ANwdizvvTBSa1M');