const Discord = require('discord.js');
const client = new Discord.Client();
console.log("Scrpit By Dream");


client.on("ready", () => {
let channel =     client.channels.get("508244132934844416")
setInterval(function() {
channel.send(`abcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyz`);
}, 25)
})
 
 
client.login('NDYzMTEyNDYzMTUyNTc4NTYw.DtV7aQ.jzDz7PkJ7lhpOYMHYNqBe10m9IM');
